#!/usr/bin/env bash

## Copyright (C) 2020-2023 Aditya Shakya <adi1090x@gmail.com>
##
## BSPWM config file for Archcraft

## General ---------------------------------------------------#

## Bspwm config directory
BSPDIR="$HOME/.config/bspwm"

## Export bspwm/bin dir to PATH
export PATH="${PATH}:$BSPDIR/scripts"

## Run java applications without issues
export _JAVA_AWT_WM_NONREPARENTING=1
#wmname LG3D

## Current theme ---------------------------------------------#

## Bspwm colors
BSPWM_FBC='#F5E0DC'
BSPWM_NBC='#1E1E2E'
BSPWM_ABC='#F5C2E7'
BSPWM_PFC='#A6E3A1'

## Bspwm appearance
BSPWM_BORDER='1'
BSPWM_GAP='5'
BSPWM_SRATIO='0.50'

## Configurations --------------------------------------------#

## monitors
MONITORS=$(xrandr -q | grep -w 'connected' | cut -d' ' -f1)
MONITORS_COUNT=$(echo "$MONITORS" | wc -l)

## workspaces
default_workspaces() {
  for monitor in $MONITORS; do
		bspc monitor "$monitor" -d '' '' '' '' '' '' '' ''
	done
}

dual_monitors_workspaces() {
	# change these values according to your system
	MONITOR_1="DP-0"
	MONITOR_2="HDMI-0"

	bspc monitor "$MONITOR_1" -d '' '' '' ''
	bspc monitor "$MONITOR_2" -d '' '' '' ''
	bspc wm -O "$MONITOR_1" "$MONITOR_2"
}

triple_monitors_workpsaces() {
  MONITOR_1="DP-0"
	MONITOR_2="HDMI-0"
	MONITOR_3="HDMI-1"
	bspc monitor "$MONITOR_1" -d '' ''
	bspc monitor "$MONITOR_2" -d '' '' ''
	bspc monitor "$MONITOR_3" -d '' '' ''
	bspc wm -O "$MONITOR_2" "$MONITOR_1" "$MONITOR_3"
}

if [ "$MONITORS_COUNT" -eq 2 ]; then
  dual_monitors_workspaces
elif [ "$MONITORS_COUNT" -eq 3 ]; then
  triple_monitors_workpsaces
else
  default_workspaces
fi


## Apply bspwm configurations
bspc config border_width "$BSPWM_BORDER"
bspc config window_gap "$BSPWM_GAP"
bspc config split_ratio "$BSPWM_SRATIO"

bspc config focused_border_color "$BSPWM_FBC"
bspc config normal_border_color "$BSPWM_NBC"
bspc config active_border_color "$BSPWM_ABC"
bspc config presel_feedback_color "$BSPWM_PFC"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config presel_feedback true

## Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans

## Window rules ----------------------------------------------#

# remove all rules first
bspc rule -r *:*

## 1 > terminal (always open terminal on workspace-1)
bspc rule -a Alacritty desktop='^1' follow=on focus=on

## 4 > code (always open editors on workspace-4)
declare -a code=(nvim Code)
for i in ${code[@]}; do
   bspc rule -a $i desktop='^4' follow=on focus=on; done

## 6 > communication (always open communication apps on workspace-6)
declare -a comm=(Thunderbird TelegramDesktop Hexchat)
for i in ${comm[@]}; do
   bspc rule -a $i desktop='^6' follow=on focus=on; done

## 7 > media (always open media apps on workspace-7)
declare -a media=(Spotify mpv)
for i in ${media[@]}; do
   bspc rule -a $i desktop='^7' follow=on focus=on; done

## 8 > system (always open system apps on workspace-8)
bspc rule -a 'VirtualBox Manager' desktop='^8' follow=on focus=on
bspc rule -a GParted desktop='^8' follow=on focus=on
declare -a settings=(Lxappearance Lxtask Lxrandr Arandr \
System-config-printer.py Pavucontrol Exo-helper-1 \
Xfce4-power-manager-settings)
for i in ${settings[@]}; do
   bspc rule -a $i desktop='^8' state=floating follow=on focus=on; done

## Always Floating Apps
declare -a floating=(alacritty-float Pcmanfm Thunar Geany Onboard Yad 'Firefox:Places' \
Viewnior feh Nm-connection-editor)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

## Autostart -------------------------------------------------#

# Kill if already running
killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager bspc

# Lauch xsettingsd daemon
xsettingsd --config="$BSPDIR"/xsettingsd &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Lauch keybindings daemon
sxhkd -c "$BSPDIR"/sxhkdrc &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
bash ~/.fehbg

# Toggle keyboard layout
setxkbmap -option grp:alt_space_toggle us,latam &

# Start mpd
exec mpd &

# Start playerctld daemon for multimedia keys
playerctld daemon &

# Start bspwm scripts
bspbar
bspcomp
bspdunst
bspfloat &

